name: code quality
on:
    pull_request:

jobs:
    qodana:
        runs-on: ubuntu-latest
        timeout-minutes: 120

        steps:
            - uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: corretto
                  java-version: 17

            - name: Download
              uses: gradle/gradle-build-action@v1
              with:
                  arguments: ":resolveDependencies -Pkotlin.incremental=false --no-daemon"

            - name: Build
              uses: gradle/gradle-build-action@v1
              with:
                  arguments: "assemble testClasses -Pkotlin.incremental=false --no-daemon"

            - name: Qodana
              uses: JetBrains/qodana-action@v2022.2.3
              with:
                  use-caches: false
